Fix NPE in DOMUtils.findElementText
When running Lemminx-Maven on VSCode (using vscode-xml extension) a following NPE may happen:

```
Message: Cannot invoke "org.eclipse.lemminx.dom.DOMElement.getChildren()" because "element" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.lemminx.dom.DOMElement.getChildren()" because "element" is null
	at org.eclipse.lemminx.extensions.maven.utils.DOMUtils.findElementText(DOMUtils.java:97)
	at org.eclipse.lemminx.extensions.maven.utils.ParticipantUtils.getMavenProperty(ParticipantUtils.java:302)
	at org.eclipse.lemminx.extensions.maven.participants.codeaction.InlinePropertyCodeAction.doCodeActionUnconditional(InlinePropertyCodeAction.java:55)
	at org.eclipse.lemminx.services.XMLCodeActions.doCodeActions(XMLCodeActions.java:81)
	at org.eclipse.lemminx.services.XMLLanguageService.doCodeActions(XMLLanguageService.java:284)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$codeAction$24(XMLTextDocumentService.java:502)
	at org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```