[tests] Fix NPE in MavenCompletionParticipantDuplicationTest
```
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "version" is null
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:543)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:534)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.parseVersion(DefaultArtifactVersion.java:94)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:44)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipantDuplicationTest$1.compare(MavenCompletionParticipantDuplicationTest.java:116)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipantDuplicationTest$1.compare(MavenCompletionParticipantDuplicationTest.java:111)
```