Fix NPE in MavenLemminxExtension.stop
```
SEVERE: Error while stopping extension <org.eclipse.lemminx.extensions.maven.MavenLemminxExtension>
java.lang.NullPointerException: Cannot invoke "org.eclipse.lemminx.extensions.maven.project.MavenProjectCache.stop()" because "this.cache" is null
	at org.eclipse.lemminx.extensions.maven.MavenLemminxExtension.stop(MavenLemminxExtension.java:554)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.unregisterExtension(XMLExtensionsRegistry.java:296)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.dispose(XMLExtensionsRegistry.java:309)
	at org.eclipse.lemminx.extensions.maven.participants.hover.MavenHoverCancellationTest.tearDown(MavenHoverCancellationTest.java:47)
```